PostgreSQL:
  restart: always
  image: sameersbn/postgresql:9.6-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - DB_USER=kbase
    - DB_PASS=password
    - DB_NAME=kbase
  volumes:
    - /Volumes/docker/postgresql:/var/lib/postgresql
