version: "3"
services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=kbase
      - DB_PASS=password
      - DB_NAME=kbase,test
    volumes:
      - /usr/local/postgresql:/var/lib/postgresql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/init.sql:/docker-entrypoint-initdb.d/test/test.sql
  kbaseui:
    restart: always
    image: jackgore/knowledge-base-ui:latest
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=http://kbase:3001
  kbase:
    restart: always
    image: jackgore/knowledge-base:latest
    ports:
      - "3001:3001"
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    ports:
      - "5601:5601"
